---
- name: "Install packages"
  retries: 3
  delay: 10
  until: output is success
  register: output
  ansible.builtin.package:
    update_cache: true
    name:
      - "unattended-upgrades"

- name: "Create Unattended-Upgrades files"
  block:
    - name: "Reset 50unattended-upgrades configuration file on Debian"
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Debian'
      ansible.builtin.copy:
        src: "50unattended-upgrades.Debian"
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        owner: "root"
        group: "root"
        mode: "0600"

    - name: "Reset 50unattended-upgrades configuration file on Ubuntu"
      changed_when: false
      when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
      ansible.builtin.copy:
        src: "50unattended-upgrades.Ubuntu"
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        owner: "root"
        group: "root"
        mode: "0600"

    - name: "Reset 20auto-upgrades configuration file"
      changed_when: false
      ansible.builtin.copy:
        src: "20auto-upgrades"
        dest: "/etc/apt/apt.conf.d/20auto-upgrades"
        owner: "root"
        group: "root"
        mode: "0600"

- name: "Configure file: 50unattended-upgrades"
  block:
    - name: "Configure Unattended-Upgrades to run updates or not at reboot"
      changed_when: false
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/50unattended-upgrades"
        line: "Unattended-Upgrade::Automatic-Reboot \"{{ install_unattended_upgrades__automatic_reboot | lower }}\";"
        state: present

    - name: "Configure updates runs at {{ install_unattended_upgrades__automatic_reboot_time }}"
      changed_when: false
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/50unattended-upgrades"
        line: "Unattended-Upgrade::Automatic-Reboot-Time \"{{ install_unattended_upgrades__automatic_reboot_time }}\";"
        state: present

    - name: "Configure email address for notifications"
      changed_when: false
      ansible.builtin.lineinfile:
        dest: "/etc/apt/apt.conf.d/50unattended-upgrades"
        line: "Unattended-Upgrade::Mail \"{{ install_unattended_upgrades__report_email_address }}\";"
        state: present

- name: "Configure file: 20auto-upgrades"
  block:
    - name: "Enable Unattended-Upgrades"
      changed_when: false
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/20auto-upgrades"
        line: "APT::Periodic::Unattended-Upgrade \"1\";"
        state: present

    - name: "Set automatic reboot"
      changed_when: false
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/20auto-upgrades"
        line: "APT::Periodic::Automatic-Reboot \"{{ install_unattended_upgrades__automatic_reboot | lower  }}\";"
        state: present

    - name: "Set automatic reboot time"
      changed_when: false
      ansible.builtin.lineinfile:
        path: "/etc/apt/apt.conf.d/20auto-upgrades"
        line: "APT::Periodic::Automatic-Reboot-Time \"{{ install_unattended_upgrades__automatic_reboot_time }}\";"
        state: present
