---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_unattended_upgrades"
      tags:
        - "labocbz.install_unattended_upgrades"
      vars:
        install_unattended_upgrades__automatic_reboot: "{{ inv_install_unattended_upgrades__automatic_reboot }}"
        install_unattended_upgrades__automatic_reboot_time: "{{ inv_install_unattended_upgrades__automatic_reboot_time }}"
        install_unattended_upgrades__report_email_address: "{{ inv_install_unattended_upgrades__report_email_address }}"
      ansible.builtin.include_role:
        name: "labocbz.install_unattended_upgrades"
